import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import '../models/trade_signal.dart';
import '../models/performance_stats.dart';

class ApiService {
  static const String baseUrl = 'https://tradingbot-dr49.onrender.com';
  
  // Timeout for mobile network requests
  static const Duration timeout = Duration(seconds: 10);

  /// Fetches real-time signals from the cloud bot.
  /// Returns only live signals generated by the bot, or empty list if none yet.
  static Future<List<TradeSignal>> fetchLiveSignals() async {
    try {
      final response = await http
          .get(Uri.parse('$baseUrl/api/signals'))
          .timeout(timeout);

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        if (data['signals'] is List) {
          return (data['signals'] as List)
              .map((item) => TradeSignal.fromJson(item as Map<String, dynamic>, isLive: true))
              .toList();
        }
      }
    } catch (e) {
      debugPrint('ApiService.fetchLiveSignals error: $e');
    }

    return [];
  }

  /// Backward-compatible method
  static Future<List<TradeSignal>> fetchSignals() async {
    final live = await fetchLiveSignals();
    return live;
  }

  /// Fetches historical backtest benchmark signals for reference & analysis demonstration
  static List<TradeSignal> getBacktestBenchmarkSignals() {
    return _getSampleBacktestSignals();
  }

  static Future<PerformanceStats> fetchStats() async {
    try {
      final response = await http
          .get(Uri.parse('$baseUrl/api/stats'))
          .timeout(timeout);

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final stats = PerformanceStats.fromJson(data);
        
        // If live bot has closed trades, return live stats
        if (stats.totalClosed > 0) {
          return stats;
        }
      }
    } catch (e) {
      debugPrint('ApiService.fetchStats error: $e');
    }

    // Fallback benchmark baseline if 0 trades closed yet
    return PerformanceStats.backtestBenchmark();
  }

  static Future<bool> checkHealth() async {
    try {
      final response = await http
          .get(Uri.parse('$baseUrl/'))
          .timeout(const Duration(seconds: 5));
      return response.statusCode == 200;
    } catch (_) {
      return false;
    }
  }

  static List<TradeSignal> _getSampleBacktestSignals() {
    return [
      TradeSignal(
        id: 'R_25_1788962700',
        symbol: 'R_25',
        pattern: 'Morning Star',
        direction: 'BUY',
        entry: 2744.37,
        sl: 2736.95,
        tp: 2755.50,
        rr: 1.5,
        timestamp: '2026-09-09 14:05:00 UTC',
        status: 'WIN',
        resultR: 1.5,
        exitPrice: 2755.50,
        exitTime: '2026-09-09 14:40:00 UTC',
        isLive: false,
      ),
      TradeSignal(
        id: 'R_25_1788960300',
        symbol: 'R_25',
        pattern: 'Morning Star',
        direction: 'BUY',
        entry: 2744.35,
        sl: 2736.94,
        tp: 2755.46,
        rr: 1.5,
        timestamp: '2026-09-09 13:25:00 UTC',
        status: 'WIN',
        resultR: 1.5,
        exitPrice: 2755.46,
        exitTime: '2026-09-09 13:50:00 UTC',
        isLive: false,
      ),
      TradeSignal(
        id: 'R_75_1788944100',
        symbol: 'R_75',
        pattern: 'Hammer',
        direction: 'BUY',
        entry: 47338.53,
        sl: 47173.79,
        tp: 48194.04,
        rr: 5.2,
        timestamp: '2026-09-09 08:55:00 UTC',
        status: 'LOSS',
        resultR: -1.0,
        exitPrice: 47173.79,
        exitTime: '2026-09-09 09:20:00 UTC',
        isLive: false,
      ),
      TradeSignal(
        id: 'R_75_1788932700',
        symbol: 'R_75',
        pattern: 'Hammer',
        direction: 'BUY',
        entry: 47203.42,
        sl: 47043.96,
        tp: 48194.04,
        rr: 6.2,
        timestamp: '2026-09-09 05:45:00 UTC',
        status: 'WIN',
        resultR: 6.2,
        exitPrice: 48194.04,
        exitTime: '2026-09-09 07:10:00 UTC',
        isLive: false,
      ),
      TradeSignal(
        id: 'R_75_1788926100',
        symbol: 'R_75',
        pattern: 'Hammer',
        direction: 'BUY',
        entry: 48771.24,
        sl: 48577.91,
        tp: 49061.22,
        rr: 1.5,
        timestamp: '2026-09-09 03:55:00 UTC',
        status: 'LOSS',
        resultR: -1.0,
        exitPrice: 48577.91,
        exitTime: '2026-09-09 04:20:00 UTC',
        isLive: false,
      ),
      TradeSignal(
        id: 'R_75_1788918900',
        symbol: 'R_75',
        pattern: 'Hammer',
        direction: 'BUY',
        entry: 49279.94,
        sl: 49009.47,
        tp: 50219.69,
        rr: 3.5,
        timestamp: '2026-09-09 01:55:00 UTC',
        status: 'LOSS',
        resultR: -1.0,
        exitPrice: 49009.47,
        exitTime: '2026-09-09 02:40:00 UTC',
        isLive: false,
      ),
      TradeSignal(
        id: 'R_75_1788912000',
        symbol: 'R_75',
        pattern: 'Morning Star',
        direction: 'BUY',
        entry: 49706.95,
        sl: 49517.95,
        tp: 49990.46,
        rr: 1.5,
        timestamp: '2026-09-09 00:00:00 UTC',
        status: 'LOSS',
        resultR: -1.0,
        exitPrice: 49517.95,
        exitTime: '2026-09-09 00:30:00 UTC',
        isLive: false,
      ),
      TradeSignal(
        id: 'R_75_1788890400',
        symbol: 'R_75',
        pattern: 'Morning Star',
        direction: 'BUY',
        entry: 47794.59,
        sl: 47376.82,
        tp: 48421.24,
        rr: 1.5,
        timestamp: '2026-09-08 18:00:00 UTC',
        status: 'WIN',
        resultR: 1.5,
        exitPrice: 48421.24,
        exitTime: '2026-09-08 19:15:00 UTC',
        isLive: false,
      ),
      TradeSignal(
        id: 'R_25_1788856200',
        symbol: 'R_25',
        pattern: 'Hammer',
        direction: 'BUY',
        entry: 2733.52,
        sl: 2725.99,
        tp: 2745.18,
        rr: 1.5,
        timestamp: '2026-09-08 08:30:00 UTC',
        status: 'WIN',
        resultR: 1.5,
        exitPrice: 2745.18,
        exitTime: '2026-09-08 09:05:00 UTC',
        isLive: false,
      ),
      TradeSignal(
        id: 'R_25_1788851700',
        symbol: 'R_25',
        pattern: 'Morning Star',
        direction: 'BUY',
        entry: 2732.29,
        sl: 2725.93,
        tp: 2745.18,
        rr: 2.0,
        timestamp: '2026-09-08 07:15:00 UTC',
        status: 'WIN',
        resultR: 2.0,
        exitPrice: 2745.18,
        exitTime: '2026-09-08 08:00:00 UTC',
        isLive: false,
      ),
    ];
  }
}
