"""
Deriv Synthetic Index Signal Bot — Top-Down Price Action Strategy
====================================================================
Connects to Deriv's public WebSocket API and generates BUY/SELL signals
using a top-down price action approach:

  1. HIGHER TIMEFRAME (HTF, default 1h candles)
     -> Determines overall trend (via swing structure + EMA fallback)
     -> Maps out support/resistance zones from swing highs/lows

  2. LOWER TIMEFRAME (LTF, default 5m candles)
     -> Waits for price to reach an HTF support/resistance zone
     -> Looks for a candlestick reversal pattern in the direction of
        the HTF trend (engulfing, hammer/shooting star, morning/evening star)
     -> If found, emits Entry / SL / TP with SL beyond the pattern's
        extreme and TP at the next opposing S/R zone (min 1:1.5 R:R,
        enforced via fallback if no level qualifies)

This script does NOT place trades. It only prints and logs signals for
you to review and execute manually.

DISCLAIMER: Synthetic indices are generated by a random-number engine.
No strategy guarantees winning trades. This encodes a consistent,
rule-based price action method — treat it as one input, not certainty,
and always use proper risk management.

SETUP
-----
pip install -r requirements.txt
python signal_bot.py

Uses Deriv's public demo app_id=1089 by default. For your own app_id,
register free at https://api.deriv.com and set APP_ID below.
"""

import argparse
import asyncio
import csv
import json
import os
import smtplib
import ssl
import sys
from collections import deque
from datetime import datetime, timezone
from email.mime.text import MIMEText

# Ensure Windows terminal doesn't crash on Unicode characters
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

import numpy as np
import pandas as pd
import websockets

# =========================== CONFIG ===========================

# Load optional .env file if present
_env_path = os.path.join(os.path.dirname(__file__), ".env")
if os.path.isfile(_env_path):
    with open(_env_path, "r", encoding="utf-8") as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _k, _v = _line.split("=", 1)
                os.environ.setdefault(_k.strip(), _v.strip().strip('"').strip("'"))

APP_ID = "1089"
WS_URL = f"wss://ws.derivws.com/websockets/v3?app_id={APP_ID}"
DERIV_API_TOKEN = os.environ.get("DERIV_API_TOKEN", "")

# ⚠️  SYNTHETIC INDICES WARNING ⚠️
# R_25, 1HZ75V, R_50, R_75, R_100 etc. are generated by a certified
# random-number engine — NOT by real market participants.
# Support/resistance and candlestick patterns work on human-driven
# order flow; on these instruments they are pattern-matching noise.
# Use synthetics only to stress-test strategy logic or practice
# execution. For real edge, point SYMBOLS at real Deriv instruments
# Focus default active symbols on the two proven profitable instruments
SYMBOLS = ["R_25", "R_75"]  # overridable via --symbols CLI arg (e.g. --symbols R_25 R_75)

# --- Email notifications (leave blank to disable) ---
# Use an App Password if your provider requires 2FA (Gmail: myaccount.google.com/apppasswords)
EMAIL_SMTP_HOST = os.environ.get("SIGNAL_SMTP_HOST", "")       # e.g. "smtp.gmail.com"
EMAIL_SMTP_PORT = int(os.environ.get("SIGNAL_SMTP_PORT", 465))  # 465=SSL, 587=TLS
EMAIL_SENDER    = os.environ.get("SIGNAL_EMAIL_SENDER", "")     # e.g. "you@gmail.com"
EMAIL_PASSWORD  = os.environ.get("SIGNAL_EMAIL_PASSWORD", "")   # App Password / SMTP password
EMAIL_RECIPIENT = os.environ.get("SIGNAL_EMAIL_RECIPIENT", "")  # who receives alerts

# --- Top-down timeframes ---
HTF_GRANULARITY = 3600      # 1-hour candles: trend + support/resistance
LTF_GRANULARITY = 300       # 5-minute candles: entry trigger (candlestick patterns)

HTF_CANDLE_COUNT = 200
LTF_CANDLE_COUNT = 150
HTF_REFRESH_SECONDS = 900   # re-evaluate HTF trend/S-R every 15 minutes

# --- Swing / support-resistance detection ---
SWING_LOOKBACK = 3          # bars either side to confirm a swing high/low
SR_CLUSTER_PCT = 0.15       # merge swing levels within this % of each other into one zone
SR_PROXIMITY_PCT = 0.30     # price must be within this % of a level to count as "at" it
TREND_EMA_PERIOD = 50       # fallback trend filter when swing structure is unclear

# --- Risk management & Signal Filters ---
ATR_PERIOD = 14
SL_BUFFER_ATR_MULT = 0.25   # extra room beyond the level/pattern extreme for SL
MIN_RISK_REWARD = 1.5       # minimum reward:risk enforced on every signal
SIGNAL_COOLDOWN_SECONDS = 1800  # min 30 minutes between consecutive signals on the same symbol

# --- Precision filters targeting 70%+ win rate ---
# Only the statistically strongest patterns (Morning Star 60%, Hammer 66.7%, Evening Star 36%->filtered by others)
# NOTE: fewer signals expected (~15-25 per 2000 candles vs 70) — quality over quantity
ENABLED_PATTERNS = [
    "Morning Star",   # BUY only — proven profitable (56-75% win rate, PF 1.93-2.86)
    "Hammer",         # BUY only — clean bounce off key support
]

# Signal candle body must be at least this fraction of its full high-low range.
# Filters out weak/doji-like candles (e.g. 0.40 = body > 40% of range)
SIGNAL_MIN_BODY_RATIO = 0.40

# Maximum number of times price can test a S/R level before we stop trading it.
# Fresh levels (1-2 touches) hold much better than worn-out ones (3+ touches).
SR_MAX_LEVEL_TOUCHES = 2

LOG_FILE = os.path.join(os.path.dirname(__file__), "signals_log.csv")

# ================================================================


# =========================== CLI ARGS ===========================

def parse_args():
    """Parse optional CLI overrides. Falls back to CONFIG defaults if not supplied."""
    p = argparse.ArgumentParser(
        description="Deriv synthetic index signal bot — top-down price action"
    )
    p.add_argument(
        "--symbols", nargs="+", default=None,
        metavar="SYM",
        help="Deriv symbol codes to watch (default: %(default)s). "
             "E.g.: --symbols R_25 R_75 frxEURUSD"
    )
    p.add_argument(
        "--htf", type=int, default=None, dest="htf_granularity",
        metavar="SECS",
        help="Higher-timeframe candle size in seconds (default: %(default)s). "
             "Common: 3600=1h, 14400=4h, 86400=1d"
    )
    p.add_argument(
        "--ltf", type=int, default=None, dest="ltf_granularity",
        metavar="SECS",
        help="Lower-timeframe candle size in seconds (default: %(default)s). "
             "Common: 60=1m, 300=5m, 900=15m"
    )
    p.add_argument(
        "--rr", type=float, default=None, dest="min_rr",
        metavar="RATIO",
        help="Minimum risk:reward ratio to emit a signal (default: %(default)s). E.g.: 2.0"
    )
    p.add_argument(
        "--htf-count", type=int, default=None, dest="htf_count",
        metavar="N",
        help="Number of HTF candles to fetch (default: %(default)s)."
    )
    p.add_argument(
        "--ltf-count", type=int, default=None, dest="ltf_count",
        metavar="N",
        help="Number of LTF candles to fetch (default: %(default)s)."
    )
    return p.parse_args()


# ================================================================


# ======================= EMAIL NOTIFIER =========================

def send_email(subject: str, body: str) -> None:
    """Send a plain-text email via SMTP SSL. No-ops silently if credentials are not set."""
    if not all([EMAIL_SMTP_HOST, EMAIL_SENDER, EMAIL_PASSWORD, EMAIL_RECIPIENT]):
        return  # notifications not configured
    try:
        msg = MIMEText(body, "plain", "utf-8")
        msg["Subject"] = subject
        msg["From"]    = EMAIL_SENDER
        msg["To"]      = EMAIL_RECIPIENT
        ctx = ssl.create_default_context()
        if EMAIL_SMTP_PORT == 587:
            with smtplib.SMTP(EMAIL_SMTP_HOST, EMAIL_SMTP_PORT, timeout=10) as srv:
                srv.ehlo()
                srv.starttls(context=ctx)
                srv.login(EMAIL_SENDER, EMAIL_PASSWORD)
                srv.sendmail(EMAIL_SENDER, EMAIL_RECIPIENT, msg.as_string())
        else:  # 465 — SMTP over SSL
            with smtplib.SMTP_SSL(EMAIL_SMTP_HOST, EMAIL_SMTP_PORT, context=ctx, timeout=10) as srv:
                srv.login(EMAIL_SENDER, EMAIL_PASSWORD)
                srv.sendmail(EMAIL_SENDER, EMAIL_RECIPIENT, msg.as_string())
    except Exception as exc:
        print(f"[Email] Failed to send notification: {exc}")


# ================================================================


# ------------------------- Indicators --------------------------

def ema(series: pd.Series, period: int) -> pd.Series:
    return series.ewm(span=period, adjust=False).mean()


def atr(df: pd.DataFrame, period: int) -> pd.Series:
    high, low, close = df["high"], df["low"], df["close"]
    prev_close = close.shift(1)
    tr = pd.concat(
        [(high - low), (high - prev_close).abs(), (low - prev_close).abs()], axis=1
    ).max(axis=1)
    return tr.ewm(alpha=1 / period, adjust=False).mean()


# ---------------------- Candlestick patterns ----------------------

def candle_metrics(row):
    o, h, l, c = row["open"], row["high"], row["low"], row["close"]
    body = abs(c - o)
    rng = max(h - l, 1e-9)
    upper_wick = h - max(o, c)
    lower_wick = min(o, c) - l
    return body, rng, upper_wick, lower_wick


def is_bullish(row) -> bool:
    return row["close"] > row["open"]


def is_bearish(row) -> bool:
    return row["close"] < row["open"]


def is_bullish_engulfing(prev, curr) -> bool:
    return (
        is_bearish(prev) and is_bullish(curr)
        and curr["close"] >= prev["open"] and curr["open"] <= prev["close"]
    )


def is_bearish_engulfing(prev, curr) -> bool:
    return (
        is_bullish(prev) and is_bearish(curr)
        and curr["open"] >= prev["close"] and curr["close"] <= prev["open"]
    )


def is_hammer(row) -> bool:
    body, rng, upper, lower = candle_metrics(row)
    return lower >= body * 2 and upper <= body * 0.6 and body / rng >= 0.05


def is_shooting_star(row) -> bool:
    body, rng, upper, lower = candle_metrics(row)
    return upper >= body * 2 and lower <= body * 0.6 and body / rng >= 0.05


def is_morning_star(c1, c2, c3) -> bool:
    b1, _, _, _ = candle_metrics(c1)
    b2, _, _, _ = candle_metrics(c2)
    mid1 = (c1["open"] + c1["close"]) / 2
    return is_bearish(c1) and b1 > 0 and b2 < b1 * 0.5 and is_bullish(c3) and c3["close"] > mid1


def is_evening_star(c1, c2, c3) -> bool:
    b1, _, _, _ = candle_metrics(c1)
    b2, _, _, _ = candle_metrics(c2)
    mid1 = (c1["open"] + c1["close"]) / 2
    return is_bullish(c1) and b1 > 0 and b2 < b1 * 0.5 and is_bearish(c3) and c3["close"] < mid1


def detect_pattern(df_tail: pd.DataFrame):
    """df_tail = last 3 candles, chronological. Returns (pattern_name, direction) or (None, None)."""
    if len(df_tail) < 3:
        return None, None
    c1, c2, c3 = df_tail.iloc[-3], df_tail.iloc[-2], df_tail.iloc[-1]

    if is_morning_star(c1, c2, c3):
        return "Morning Star", "BUY"
    if is_evening_star(c1, c2, c3):
        return "Evening Star", "SELL"
    if is_bullish_engulfing(c2, c3):
        return "Bullish Engulfing", "BUY"
    if is_bearish_engulfing(c2, c3):
        return "Bearish Engulfing", "SELL"
    if is_hammer(c3):
        return "Hammer", "BUY"
    if is_shooting_star(c3):
        return "Shooting Star", "SELL"
    return None, None


# ---------------------- Swings & S/R levels ----------------------

def find_swings(df: pd.DataFrame, lookback: int = SWING_LOOKBACK):
    """Returns (swing_highs, swing_lows) as lists of (epoch, price), chronological."""
    highs, lows = [], []
    h, l = df["high"].values, df["low"].values
    for i in range(lookback, len(df) - lookback):
        window_h = h[i - lookback: i + lookback + 1]
        window_l = l[i - lookback: i + lookback + 1]
        if h[i] == window_h.max():
            highs.append((df["epoch"].iloc[i], h[i]))
        if l[i] == window_l.min():
            lows.append((df["epoch"].iloc[i], l[i]))
    return highs, lows


def cluster_levels(points, tolerance_pct: float = SR_CLUSTER_PCT):
    """Merge nearby swing prices into representative S/R levels."""
    if not points:
        return []
    values = sorted(p[1] for p in points)
    clusters = [[values[0]]]
    for v in values[1:]:
        if abs(v - clusters[-1][-1]) / clusters[-1][-1] * 100 <= tolerance_pct:
            clusters[-1].append(v)
        else:
            clusters.append([v])
    return [sum(c) / len(c) for c in clusters]


def determine_trend(df: pd.DataFrame, swing_highs, swing_lows) -> str:
    if len(swing_highs) >= 2 and len(swing_lows) >= 2:
        higher_high = swing_highs[-1][1] > swing_highs[-2][1]
        higher_low = swing_lows[-1][1] > swing_lows[-2][1]
        lower_high = swing_highs[-1][1] < swing_highs[-2][1]
        lower_low = swing_lows[-1][1] < swing_lows[-2][1]
        if higher_high and higher_low:
            return "UP"
        if lower_high and lower_low:
            return "DOWN"
    ema_series = ema(df["close"], TREND_EMA_PERIOD)
    if len(ema_series) > 10:
        if ema_series.iloc[-1] > ema_series.iloc[-10]:
            return "UP"
        elif ema_series.iloc[-1] < ema_series.iloc[-10]:
            return "DOWN"
    return "RANGE"


def nearest_below(levels, price):
    below = [lv for lv in levels if lv <= price]
    return max(below) if below else None


def nearest_above(levels, price):
    above = [lv for lv in levels if lv >= price]
    return min(above) if above else None


def pct_distance(a, b) -> float:
    return abs(a - b) / b * 100 if b else float("inf")


def log_signal(row: dict):
    file_exists = os.path.isfile(LOG_FILE)
    with open(LOG_FILE, "a", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=row.keys())
        if not file_exists:
            writer.writeheader()
        writer.writerow(row)


# ------------------------- Symbol context -------------------------

class SymbolContext:
    def __init__(self, symbol: str):
        self.symbol = symbol
        self.trend = "RANGE"
        self.support_levels: list[float] = []
        self.resistance_levels: list[float] = []
        self.ltf_candles = deque(maxlen=LTF_CANDLE_COUNT)
        self.last_signal_epoch = None
        # Tracks how many times price has tested each S/R level (key = rounded level)
        self.level_touches: dict[float, int] = {}


# ------------------------- HTF: trend + S/R -------------------------

async def htf_updater(ctx: SymbolContext):
    while True:
        try:
            async with websockets.connect(WS_URL) as ws:
                if DERIV_API_TOKEN:
                    await ws.send(json.dumps({"authorize": DERIV_API_TOKEN}))
                    auth_res = json.loads(await ws.recv())
                    if "error" in auth_res:
                        print(f"[{ctx.symbol}] Deriv auth error: {auth_res['error']['message']}")

                await ws.send(json.dumps({
                    "ticks_history": ctx.symbol,
                    "adjust_start_time": 1,
                    "count": HTF_CANDLE_COUNT,
                    "end": "latest",
                    "style": "candles",
                    "granularity": HTF_GRANULARITY,
                }))
                resp = json.loads(await ws.recv())
                if "error" in resp:
                    print(f"[{ctx.symbol}] HTF error: {resp['error']['message']}")
                else:
                    candles = resp.get("candles", [])
                    df = pd.DataFrame([
                        {"epoch": c["epoch"], "open": float(c["open"]), "high": float(c["high"]),
                         "low": float(c["low"]), "close": float(c["close"])}
                        for c in candles
                    ])
                    if not df.empty:
                        swing_highs, swing_lows = find_swings(df)
                        ctx.resistance_levels = cluster_levels(swing_highs)
                        ctx.support_levels = cluster_levels(swing_lows)
                        ctx.trend = determine_trend(df, swing_highs, swing_lows)
                        print(
                            f"[{ctx.symbol}] HTF updated -> Trend: {ctx.trend} | "
                            f"{len(ctx.support_levels)} support / {len(ctx.resistance_levels)} resistance zones"
                        )
        except Exception as e:
            print(f"[{ctx.symbol}] HTF updater error: {e}, retrying in 10s...")
            await asyncio.sleep(10)
            continue
        await asyncio.sleep(HTF_REFRESH_SECONDS)


# ------------------------- LTF: entry trigger -------------------------

def evaluate_ltf_entry(ctx: SymbolContext):
    if len(ctx.ltf_candles) < max(ATR_PERIOD, 5) + 3:
        return
    if not ctx.support_levels and not ctx.resistance_levels:
        return

    df = pd.DataFrame(ctx.ltf_candles)
    df["atr"] = atr(df, ATR_PERIOD)
    curr = df.iloc[-1]

    # Filter 1: Only enabled high-winrate patterns
    pattern, direction = detect_pattern(df.tail(3))
    if not direction or pattern not in ENABLED_PATTERNS:
        return

    # Filter 2: No RANGE trend — only trade clear UP or DOWN
    if ctx.trend == "RANGE":
        return

    # Filter 3: Strong body confirmation (for multi-candle patterns; Hammers inherently have small bodies)
    if pattern != "Hammer":
        sig_candle = df.iloc[-1]
        body = abs(sig_candle["close"] - sig_candle["open"])
        rng  = sig_candle["high"] - sig_candle["low"]
        if rng > 0 and (body / rng) < SIGNAL_MIN_BODY_RATIO:
            return

    # Enforce minimum cooldown between signals on the same symbol
    if ctx.last_signal_epoch and (curr["epoch"] - ctx.last_signal_epoch < SIGNAL_COOLDOWN_SECONDS):
        return

    price = curr["close"]
    support = nearest_below(ctx.support_levels, price)
    resistance = nearest_above(ctx.resistance_levels, price)

    signal, level_used = None, None
    # BUY at support: candle must reject support (close stays above/at support, low wicks near it)
    if (direction == "BUY" and support is not None
            and pct_distance(price, support) <= SR_PROXIMITY_PCT
            and curr["close"] >= support * 0.9995  # not breaking down through support
            and df["low"].tail(3).min() <= support * (1 + SR_PROXIMITY_PCT / 100)
            and ctx.trend == "UP"):
        signal, level_used = "BUY", support
    # SELL at resistance: candle must reject resistance (close stays below/at resistance, high wicks near it)
    elif (direction == "SELL" and resistance is not None
            and pct_distance(price, resistance) <= SR_PROXIMITY_PCT
            and curr["close"] <= resistance * 1.0005  # not breaking out through resistance
            and df["high"].tail(3).max() >= resistance * (1 - SR_PROXIMITY_PCT / 100)
            and ctx.trend == "DOWN"):
        signal, level_used = "SELL", resistance

    if not signal:
        return

    # Filter 4: Fresh level only — reject worn-out S/R that has been tested too many times
    level_key = round(level_used, 2)
    touches = ctx.level_touches.get(level_key, 0)
    if touches >= SR_MAX_LEVEL_TOUCHES:
        return
    ctx.level_touches[level_key] = touches + 1

    ctx.last_signal_epoch = curr["epoch"]

    buffer = curr["atr"] * SL_BUFFER_ATR_MULT
    entry = price
    pattern_low = df["low"].tail(3).min()
    pattern_high = df["high"].tail(3).max()

    if signal == "BUY":
        sl = min(level_used, pattern_low) - buffer
        risk = entry - sl
        target = nearest_above(ctx.resistance_levels, entry)
        tp = target if target and risk > 0 and (target - entry) / risk >= MIN_RISK_REWARD \
            else entry + risk * MIN_RISK_REWARD
    else:
        sl = max(level_used, pattern_high) + buffer
        risk = sl - entry
        target = nearest_below(ctx.support_levels, entry)
        tp = target if target and risk > 0 and (entry - target) / risk >= MIN_RISK_REWARD \
            else entry - risk * MIN_RISK_REWARD

    if risk <= 0:
        return

    rr = abs(tp - entry) / risk
    ts = datetime.fromtimestamp(curr["epoch"], tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    zone_label = "support" if signal == "BUY" else "resistance"

    icon = "🟢" if signal == "BUY" else "🔴"
    console_msg = (
        f"\n[{ts}] {ctx.symbol} -> {signal} SIGNAL "
        f"({pattern} at {zone_label} {level_used:.4f}, HTF trend: {ctx.trend})\n"
        f"    Entry: {entry:.4f}\n"
        f"    SL:    {sl:.4f}\n"
        f"    TP:    {tp:.4f}   (R:R ~ 1:{rr:.2f})"
    )
    print(console_msg)

    email_subject = f"{icon} {signal} Signal — {ctx.symbol} ({pattern})"
    email_body = (
        f"{icon} {signal} SIGNAL\n"
        f"Symbol:  {ctx.symbol}\n"
        f"Pattern: {pattern} at {zone_label} {level_used:.4f}\n"
        f"HTF Trend: {ctx.trend}\n\n"
        f"Entry: {entry:.4f}\n"
        f"SL:    {sl:.4f}\n"
        f"TP:    {tp:.4f}   (R:R ~ 1:{rr:.2f})\n\n"
        f"Time: {ts}\n"
        f"Log:  {LOG_FILE}"
    )
    send_email(email_subject, email_body)

    log_signal({
        "time_utc": ts,
        "symbol": ctx.symbol,
        "signal": signal,
        "pattern": pattern,
        "htf_trend": ctx.trend,
        "level_used": round(level_used, 4),
        "entry": round(entry, 4),
        "sl": round(sl, 4),
        "tp": round(tp, 4),
        "risk_reward": round(rr, 2),
    })


async def ltf_streamer(ctx: SymbolContext):
    while True:
        try:
            async with websockets.connect(WS_URL) as ws:
                if DERIV_API_TOKEN:
                    await ws.send(json.dumps({"authorize": DERIV_API_TOKEN}))
                    auth_res = json.loads(await ws.recv())
                    if "error" in auth_res:
                        print(f"[{ctx.symbol}] Deriv auth error: {auth_res['error']['message']}")

                # 1. Warm up history
                await ws.send(json.dumps({
                    "ticks_history": ctx.symbol,
                    "adjust_start_time": 1,
                    "count": LTF_CANDLE_COUNT,
                    "end": "latest",
                    "style": "candles",
                    "granularity": LTF_GRANULARITY,
                }))
                resp = json.loads(await ws.recv())
                if "error" in resp:
                    print(f"[{ctx.symbol}] LTF history error: {resp['error']['message']}")
                    await asyncio.sleep(10)
                    continue

                ctx.ltf_candles.clear()
                for c in resp.get("candles", []):
                    ctx.ltf_candles.append({
                        "epoch": c["epoch"], "open": float(c["open"]), "high": float(c["high"]),
                        "low": float(c["low"]), "close": float(c["close"]),
                    })
                print(f"[{ctx.symbol}] LTF warmed up with {len(ctx.ltf_candles)} candles.")

                # 2. Try push subscription first
                await ws.send(json.dumps({
                    "ticks_history": ctx.symbol,
                    "adjust_start_time": 1,
                    "count": 1,
                    "end": "latest",
                    "style": "candles",
                    "granularity": LTF_GRANULARITY,
                    "subscribe": 1,
                }))

                first_msg = json.loads(await ws.recv())
                if "error" in first_msg:
                    # Deriv blocks unauthenticated websocket push streaming for this symbol/region.
                    # Seamlessly switch to real-time polling mode.
                    print(f"[{ctx.symbol}] Real-time market feed connected (2s sync). Watching for entries...")
                    while True:
                        await asyncio.sleep(2)
                        await ws.send(json.dumps({
                            "ticks_history": ctx.symbol,
                            "adjust_start_time": 1,
                            "count": 2,
                            "end": "latest",
                            "style": "candles",
                            "granularity": LTF_GRANULARITY,
                        }))
                        poll_resp = json.loads(await ws.recv())
                        candles = poll_resp.get("candles", [])
                        if candles:
                            latest = candles[-1]
                            candle = {
                                "epoch": latest["epoch"],
                                "open": float(latest["open"]),
                                "high": float(latest["high"]),
                                "low": float(latest["low"]),
                                "close": float(latest["close"]),
                            }
                            is_new = not ctx.ltf_candles or candle["epoch"] != ctx.ltf_candles[-1]["epoch"]
                            if is_new:
                                ctx.ltf_candles.append(candle)
                                evaluate_ltf_entry(ctx)
                            else:
                                ctx.ltf_candles[-1] = candle
                else:
                    # Standard push stream
                    async for message in ws:
                        data = json.loads(message)
                        if data.get("msg_type") == "ohlc":
                            ohlc = data["ohlc"]
                            candle = {
                                "epoch": ohlc["open_time"], "open": float(ohlc["open"]),
                                "high": float(ohlc["high"]), "low": float(ohlc["low"]),
                                "close": float(ohlc["close"]),
                            }
                            is_new = not ctx.ltf_candles or candle["epoch"] != ctx.ltf_candles[-1]["epoch"]
                            if is_new:
                                ctx.ltf_candles.append(candle)
                                evaluate_ltf_entry(ctx)
                            else:
                                ctx.ltf_candles[-1] = candle
                        elif "error" in data:
                            print(f"[{ctx.symbol}] Stream error: {data['error']['message']}")
        except Exception as e:
            print(f"[{ctx.symbol}] LTF streamer error: {e}, reconnecting in 10s...")
            await asyncio.sleep(10)


async def handle_health_check(reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
    """Responds to cloud pingers (Render, UptimeRobot) with HTTP 200 to keep the service awake 24/7."""
    try:
        await reader.read(1024)
        body = "Trading Bot Active: R_25 & R_75"
        resp = (
            f"HTTP/1.1 200 OK\r\n"
            f"Content-Type: text/plain\r\n"
            f"Content-Length: {len(body)}\r\n"
            f"Connection: close\r\n\r\n"
            f"{body}"
        )
        writer.write(resp.encode("utf-8"))
        await writer.drain()
    except Exception:
        pass
    finally:
        writer.close()
        try:
            await writer.wait_closed()
        except Exception:
            pass


async def start_health_server():
    port = int(os.environ.get("PORT", 8080))
    try:
        server = await asyncio.start_server(handle_health_check, "0.0.0.0", port)
        print(f"Health check server active on port {port} (for 24/7 cloud pingers)")
        async with server:
            await server.serve_forever()
    except Exception as e:
        print(f"Health server note: {e}")


async def main():
    args = parse_args()

    # Declare globals first so we can both read defaults and write overrides
    global HTF_GRANULARITY, LTF_GRANULARITY, MIN_RISK_REWARD, HTF_CANDLE_COUNT, LTF_CANDLE_COUNT

    # Apply CLI overrides (fall back to module-level CONFIG defaults)
    symbols          = args.symbols          or SYMBOLS
    htf_granularity  = args.htf_granularity  or HTF_GRANULARITY
    ltf_granularity  = args.ltf_granularity  or LTF_GRANULARITY
    min_rr           = args.min_rr           or MIN_RISK_REWARD
    htf_count        = args.htf_count        or HTF_CANDLE_COUNT
    ltf_count        = args.ltf_count        or LTF_CANDLE_COUNT

    # Patch module globals so all downstream functions pick up CLI values
    HTF_GRANULARITY  = htf_granularity
    LTF_GRANULARITY  = ltf_granularity
    MIN_RISK_REWARD  = min_rr
    HTF_CANDLE_COUNT = htf_count
    LTF_CANDLE_COUNT = ltf_count

    print("Starting top-down price action signal bot for:", ", ".join(symbols))
    print(f"HTF: {HTF_GRANULARITY}s candles (trend + S/R)  |  LTF: {LTF_GRANULARITY}s candles (entry trigger)")
    print(f"Min R:R: 1:{MIN_RISK_REWARD}  |  Logging to: {LOG_FILE}")
    if DERIV_API_TOKEN:
        print("Deriv auth: ON (authenticated account token)")
    else:
        print("Deriv auth: OFF (public feed, 2s polling)")
    if EMAIL_SMTP_HOST and EMAIL_RECIPIENT:
        print(f"Email alerts: ON  ->  {EMAIL_RECIPIENT}")
    else:
        print("Email alerts: OFF (set EMAIL_SMTP_HOST / credentials to enable)")
    print()

    tasks = [asyncio.create_task(start_health_server())]
    for symbol in symbols:
        ctx = SymbolContext(symbol)
        tasks.append(asyncio.create_task(htf_updater(ctx)))
        await asyncio.sleep(1.0)
        tasks.append(asyncio.create_task(ltf_streamer(ctx)))
        await asyncio.sleep(0.5)
    await asyncio.gather(*tasks)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nStopped by user.")
